// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNkGaA71NVsDb0TY_-1VvgG4IX3cKoy8M',
    appId: '1:797493748621:web:ae6644e1e32edf52b453c4',
    messagingSenderId: '797493748621',
    projectId: 'tanakh-reader',
    authDomain: 'tanakh-reader.firebaseapp.com',
    databaseURL: 'https://tanakh-reader-default-rtdb.firebaseio.com',
    storageBucket: 'tanakh-reader.appspot.com',
    measurementId: 'G-87LVD3ECEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD78IQRs1vRUX9NcBjg1zJDMVokVxzQB4',
    appId: '1:797493748621:android:fb27cba95763520cb453c4',
    messagingSenderId: '797493748621',
    projectId: 'tanakh-reader',
    databaseURL: 'https://tanakh-reader-default-rtdb.firebaseio.com',
    storageBucket: 'tanakh-reader.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiuYmH0jmMQfRhwQiHphERQEh8ziS322o',
    appId: '1:797493748621:ios:fe9d611992bb2f2fb453c4',
    messagingSenderId: '797493748621',
    projectId: 'tanakh-reader',
    databaseURL: 'https://tanakh-reader-default-rtdb.firebaseio.com',
    storageBucket: 'tanakh-reader.appspot.com',
    iosClientId: '797493748621-3n97r4buadqcugjq1bp2lmq2gbk61b46.apps.googleusercontent.com',
    iosBundleId: 'com.example.hebrewLiteracyApp',
  );
}
